name: Publish & Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      ref_name:
        description: 'Git tag to publish & release'
        type: string
        required: true
      #todo: add option to skip publish-vs-marketplace

jobs:
  delivery:
    runs-on: ubuntu-latest
    #todo: make the whole thing more granular: prep, publish-vs-marketplace, release-github
    #       and update things accordingly: contents:w to release-github; VSCE_PAT to publish-vs-marketplace, etc.
    permissions:
      contents: write
    env:
      # e.g.: "v2.3.2"
      VERSION_NAME: ${{ inputs.ref_name || github.ref_name }}

    steps:
      - name: Compute version number
        id: version-number
        run: |
          # i.e.: drop the 'v' from 'vX.Y.Z'
          name="${{ env.VERSION_NAME }}"
          number=$(echo $name | sed 's/v//')
          echo "VERSION_NUMBER=$number" >> "$GITHUB_ENV"
          echo "OUT=$number" >> "$GITHUB_OUTPUT"

      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.VERSION_NAME }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          npm install --global @vscode/vsce

      - name: Build the theme
        run: npm run build

      - name: Package the extension
        run: |
          vsce package $VERSION_NUMBER \
              --no-git-tag-version --no-update-package-json
          # packages as "lucario-theme-$VERSION_NUMBER.vsix"

      #todo restore Publish step
      #nice publish to Open VSX Registry

      - name: Gather release assets
        run: |
          scripts/extract_version_changelog.sh > RELEASE_BODY.md
          mkdir release-assets
          cp "lucario-theme-$VERSION_NUMBER.vsix" release-assets
          json_assets_path="release-assets/Lucario-color-theme-$VERSION_NUMBER.json"
          cp themes/Lucario-color-theme.json "$json_assets_path"

      #todo: don't use tags cause they're insecure
      - name: Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: ${{ env.VERSION_NAME }}
          tag_name: ${{ env.VERSION_NAME }}
          files: release-assets/*
          body_path: RELEASE_BODY.md
          generate_release_notes: true # appends the "Full Changelog" link to RELEASE_BODY.md
          make_latest: false # true would be problematic if we release a v1 minor version
